[package]
name = "tab_pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","lib"]

[dependencies]
anchor-lang = "0.30.0"

[profile.release]
overflow-checks = true

[features]
idl-build = ["anchor-lang/idl-build"]
